# Generated by Django 5.0.2 on 2024-02-29 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MeadowApps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='author_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeadowApps.student'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='author_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeadowApps.student'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MeadowApps.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='MeadowApps.student'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeadowApps.student'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeadowApps.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeadowApps.teacher'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeadowApps.teacher'),
        ),
    ]
