# Generated by Django 5.0.2 on 2024-02-29 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeadowApps', '0002_initial'),
        ('MeadowUsers', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeadowUsers.student'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MeadowUsers.student'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='author_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeadowUsers.student'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeadowUsers.student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='MeadowUsers.student'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
