# Generated by Django 5.0.2 on 2024-02-29 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeadowApps', '0003_alter_comment_author_student_alter_enrolment_student_and_more'),
        ('MeadowUsers', '0003_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeadowUsers.teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeadowUsers.teacher'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeadowUsers.teacher'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
