# Generated by Django 5.0.2 on 2024-03-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeadowApps', '0004_alter_post_author_teacher_alter_course_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('E', 'Enrolled'), ('C', 'Cancelled')], default='P', max_length=1),
        ),
    ]
