# Generated by Django 5.0.2 on 2024-03-01 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeadowApps', '0005_alter_enrolment_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolment',
            old_name='payment_status',
            new_name='enrolment_status',
        ),
    ]
