# Generated by Django 5.0.3 on 2024-03-06 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeadowApps', '0007_courseimage'),
        ('MeadowUsers', '0004_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MeadowUsers.student'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MeadowUsers.teacher'),
        ),
    ]
