# Generated by Django 5.0.3 on 2024-03-07 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeadowApps', '0008_alter_post_author_student_alter_post_author_teacher'),
        ('MeadowUsers', '0004_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MeadowUsers.student'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MeadowUsers.teacher'),
        ),
    ]
