# Generated by Django 5.0.3 on 2024-03-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeadowApps', '0009_alter_comment_author_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
