# Generated by Django 5.0.2 on 2024-02-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeadowUsers', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('Mr.', 'Mr.'), ('Miss.', 'Miss.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Mdm.', 'Mdm.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], default='', max_length=10)),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('phone', models.CharField(default='', max_length=255)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
